version: 2
jobs:
  build:
    working_directory: /
    docker:
      - image: eranws/run-all-red-rebol2-debian

    steps:
      - run:
          name: run-all
          command: 'rebol -s /red-master/run-all.r --batch'
      - store_artifacts:
          path: /red-master/quick-test/quick-test.log
          prefix: tests
